apiVersion: v1
kind: Service
metadata:
  name: publisher
  namespace: dapr-demo
  labels:
    app: publisher
spec:
  type: ClusterIP
  selector:
    app: publisher
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
