apiVersion: v1
kind: Service
metadata:
  name: subscriber
  namespace: dapr-demo
  labels:
    app: subscriber
spec:
  type: ClusterIP
  selector:
    app: subscriber
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
    name: http
